language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install:
  - echo "memory_limit=1G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

sudo: false

env:
  matrix:
    - NETCOMMONS_VERSION=master DB=mysql
  global:
    - secure: "mNCWxN1ca61ONesx20ZieW7A8sYXBpGE2KND8si8UpEqLpdfoSAESpdQnldBIMFEtds8MJS/zpT36wojkmRdtnuOvajs5LvGV54Jr6wjvd2BouzdQqm0BW+jDkonS2N9arD6GFR6ZjSLis5PzU3HXoSjDIvGAUc3cAv6k51CdgQ="
    - GIT_COMMITTER_NAME=s-nakajima
    - GIT_COMMITTER_EMAIL=nakajimashouhei@gmail.com
    - GIT_AUTHOR_NAME=s-nakajima
    - GIT_AUTHOR_EMAIL=nakajimashouhei@gmail.com

before_script:
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - travis_wait . tools/build/plugins/cakephp/travis/pre.sh
  - . tools/build/plugins/cakephp/travis/environment.sh

script:
  - . tools/build/plugins/cakephp/travis/main.sh

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
